---
name: CD - Deploy After Successful Build

on:
  workflow_run:
    workflows: ["CI - Build, Scan, Test, Lint"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: []
    strategy:
      matrix:
        service: [api, worker]

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.service }}-artifact
          path: ./${{ matrix.service }}

      - name: Display artifact structure
        run: |
          echo "Contents of ${{ matrix.service }}:"
          ls -R ./${{ matrix.service }}

      - name: Deploy ${{ matrix.service }} container
        run: |
          echo "This is where deployment would happen."
          echo "In a real scenario, push image or apply to k8s."
